name: test golibs

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: tests
        run: |
          go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: add coverage
        run: bash <(curl -s https://codecov.io/bash)

  notify:
    needs:
      - tests
      - coverage
    # Secrets are not passed to workflows that are triggered by a pull request
    # from a fork.
    #
    # Use always() to signal to the runner that this job must run even if the
    # previous ones failed.
    if:
      ${{ always() &&
        (
          github.event_name == 'push' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v1
      - name: Send Slack notif
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo, message, commit, author, job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
